# Generated by Django 5.0.1 on 2026-01-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frameworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("INVESTIGATING", "Investigating"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("source_system", models.CharField(max_length=100)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("destination_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("affected_user", models.CharField(blank=True, max_length=255)),
                ("affected_asset", models.CharField(blank=True, max_length=255)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("time_to_detect", models.DurationField(blank=True, null=True)),
                ("time_to_respond", models.DurationField(blank=True, null=True)),
                ("time_to_resolve", models.DurationField(blank=True, null=True)),
                ("raw_log", models.JSONField(blank=True, default=dict)),
                (
                    "indicators_of_compromise",
                    models.JSONField(blank=True, default=list),
                ),
                ("enrichment_data", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("analyst_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diamond_adversary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frameworks.diamondadversary",
                    ),
                ),
                (
                    "diamond_capability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frameworks.diamondcapability",
                    ),
                ),
                (
                    "diamond_infrastructure",
                    models.ManyToManyField(
                        blank=True, to="frameworks.diamondinfrastructure"
                    ),
                ),
                (
                    "diamond_victim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frameworks.diamondvictim",
                    ),
                ),
                (
                    "kill_chain_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frameworks.killchainstage",
                    ),
                ),
                (
                    "mitre_sub_techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alerts",
                        to="frameworks.mitresubtechnique",
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alerts",
                        to="frameworks.mitretechnique",
                    ),
                ),
                (
                    "owasp_categories",
                    models.ManyToManyField(
                        blank=True, related_name="alerts", to="frameworks.owaspcategory"
                    ),
                ),
                (
                    "stride_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alerts",
                        to="frameworks.stridecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="alerts.alert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
