# Generated by Django 5.0.1 on 2026-01-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("MALWARE", "Malware"),
                            ("PHISHING", "Phishing"),
                            ("DATA_BREACH", "Data Breach"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                            ("DENIAL_OF_SERVICE", "Denial of Service"),
                            ("RANSOMWARE", "Ransomware"),
                            ("WEB_ATTACK", "Web Attack"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("CONTAINED", "Contained"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("affected_systems", models.JSONField(blank=True, default=list)),
                ("affected_users", models.JSONField(blank=True, default=list)),
                ("business_impact", models.TextField(blank=True)),
                ("containment_actions", models.TextField(blank=True)),
                ("eradication_actions", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alerts",
                    models.ManyToManyField(related_name="incidents", to="alerts.alert"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
    ]
