# Generated by Django 5.0.1 on 2026-01-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_alerts", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                ("high_alerts", models.IntegerField(default=0)),
                ("medium_alerts", models.IntegerField(default=0)),
                ("low_alerts", models.IntegerField(default=0)),
                ("resolved_alerts", models.IntegerField(default=0)),
                ("false_positives", models.IntegerField(default=0)),
                ("total_incidents", models.IntegerField(default=0)),
                ("open_incidents", models.IntegerField(default=0)),
                ("closed_incidents", models.IntegerField(default=0)),
                ("avg_time_to_detect", models.FloatField(blank=True, null=True)),
                ("avg_time_to_respond", models.FloatField(blank=True, null=True)),
                ("avg_time_to_resolve", models.FloatField(blank=True, null=True)),
                ("playbooks_executed", models.IntegerField(default=0)),
                ("playbooks_successful", models.IntegerField(default=0)),
                ("top_mitre_techniques", models.JSONField(blank=True, default=dict)),
                ("top_source_ips", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ioc_type",
                    models.CharField(
                        choices=[
                            ("IP", "IP Address"),
                            ("DOMAIN", "Domain"),
                            ("URL", "URL"),
                            ("HASH", "File Hash"),
                            ("EMAIL", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ioc_value", models.CharField(db_index=True, max_length=500)),
                ("threat_type", models.CharField(max_length=100)),
                ("confidence_score", models.IntegerField()),
                ("severity", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_seen"],
                "unique_together": {("ioc_type", "ioc_value", "source")},
            },
        ),
    ]
