# Generated by Django 5.0.1 on 2026-01-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("frameworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "playbook_type",
                    models.CharField(
                        choices=[
                            ("DETECTION", "Detection"),
                            ("CONTAINMENT", "Containment"),
                            ("ERADICATION", "Eradication"),
                            ("RECOVERY", "Recovery"),
                            ("INVESTIGATION", "Investigation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("script_path", models.CharField(max_length=500)),
                ("timeout_seconds", models.IntegerField(default=300)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_execute", models.BooleanField(default=False)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kill_chain_stages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playbooks",
                        to="frameworks.killchainstage",
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playbooks",
                        to="frameworks.mitretechnique",
                    ),
                ),
                (
                    "owasp_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playbooks",
                        to="frameworks.owaspcategory",
                    ),
                ),
                (
                    "stride_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playbooks",
                        to="frameworks.stridecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("actions_taken", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_executions",
                        to="alerts.alert",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="playbooks.playbook",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
