# Generated by Django 5.0.1 on 2026-01-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiamondAdversary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "motivation",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial"),
                            ("ESPIONAGE", "Espionage"),
                            ("DISRUPTION", "Disruption"),
                            ("IDEOLOGY", "Ideological"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sophistication_level",
                    models.CharField(
                        choices=[
                            ("NOVICE", "Novice"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                            ("NATION_STATE", "Nation State"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Diamond Adversaries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiamondVictim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=200)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("FINANCE", "Financial Services"),
                            ("HEALTHCARE", "Healthcare"),
                            ("TECHNOLOGY", "Technology"),
                            ("GOVERNMENT", "Government"),
                            ("EDUCATION", "Education"),
                            ("RETAIL", "Retail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Diamond Victims",
                "ordering": ["organization"],
            },
        ),
        migrations.CreateModel(
            name="KillChainStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_number",
                    models.IntegerField(
                        choices=[
                            (1, "Reconnaissance"),
                            (2, "Weaponization"),
                            (3, "Delivery"),
                            (4, "Exploitation"),
                            (5, "Installation"),
                            (6, "Command & Control"),
                            (7, "Actions on Objectives"),
                        ],
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("indicators", models.TextField()),
                ("defensive_actions", models.TextField()),
                ("example_tools", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["stage_number"],
            },
        ),
        migrations.CreateModel(
            name="MitreTactic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tactic_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tactic_id"],
            },
        ),
        migrations.CreateModel(
            name="StrideCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stride_type",
                    models.CharField(
                        choices=[
                            ("S", "Spoofing"),
                            ("T", "Tampering"),
                            ("R", "Repudiation"),
                            ("I", "Information Disclosure"),
                            ("D", "Denial of Service"),
                            ("E", "Elevation of Privilege"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("examples", models.TextField()),
                ("countermeasures", models.TextField()),
                ("security_property", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["stride_type"],
            },
        ),
        migrations.CreateModel(
            name="MitreTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technique_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("platforms", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tactics",
                    models.ManyToManyField(
                        related_name="techniques", to="frameworks.mitretactic"
                    ),
                ),
            ],
            options={
                "ordering": ["technique_id"],
            },
        ),
        migrations.CreateModel(
            name="MitreSubTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_technique_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_techniques",
                        to="frameworks.mitretechnique",
                    ),
                ),
            ],
            options={
                "ordering": ["sub_technique_id"],
            },
        ),
        migrations.CreateModel(
            name="DiamondCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "capability_type",
                    models.CharField(
                        choices=[
                            ("MALWARE", "Malware"),
                            ("EXPLOIT", "Exploit"),
                            ("TOOL", "Tool"),
                            ("TECHNIQUE", "Technique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adversaries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="capabilities",
                        to="frameworks.diamondadversary",
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="capabilities",
                        to="frameworks.mitretechnique",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diamond Capabilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OwaspCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(max_length=10)),
                (
                    "year",
                    models.CharField(
                        choices=[("2021", "2021"), ("2017", "2017")], max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "risk_rating",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remediation", models.TextField()),
                ("cwe_mapping", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["year", "category_id"],
                "unique_together": {("category_id", "year")},
            },
        ),
        migrations.CreateModel(
            name="DiamondInfrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "infra_type",
                    models.CharField(
                        choices=[
                            ("IP", "IP Address"),
                            ("DOMAIN", "Domain"),
                            ("EMAIL", "Email"),
                            ("URL", "URL"),
                            ("SERVER", "Server"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=500)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_malicious", models.BooleanField(default=False)),
                ("reputation_score", models.IntegerField(blank=True, null=True)),
                (
                    "adversaries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="infrastructure",
                        to="frameworks.diamondadversary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diamond Infrastructure",
                "unique_together": {("infra_type", "value")},
            },
        ),
    ]
